# -*- coding: utf-8 -*-
"""Ciclos_HydroBR_ANA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uXHHoi8Vt-tEFd6yCk_zONmdHvLrKuqB

# 📊 Projeto de Ciência de Dados

# Modelagem, Detecção e Predição dos Ciclos Hidrológicos do Pantanal

---

## 🌎 1. Contexto

O **Pantanal** é a maior planície alagável tropical do mundo, com dinâmica hidrológica altamente sazonal. A alternância entre cheias e secas impacta biodiversidade, economia, navegação, agricultura e segurança hídrica.

Este projeto visa modelar quantitativamente esses ciclos e investigar possíveis mudanças estruturais ao longo das últimas décadas.

---

## 🎯 2. Problema de Pesquisa

> **Qual é a dinâmica, frequência, intensidade, espacialização e tendência dos ciclos de cheias e secas no Pantanal ao longo das últimas décadas (anual, mensal e diária)?**

### Questões complementares:

* É possível detectar mudanças estruturais no regime hidrológico?
* Há intensificação de eventos extremos?
* Podemos prever eventos futuros com modelos estatísticos e Deep Learning?
* Podemos segmentar os padrões por município?

---

## 🗂️ 3. Fonte de Dados

Os dados serão obtidos via pacote **HydroBR**, que fornece acesso estruturado às bases da **Agência Nacional de Águas (ANA)**.

### Variáveis disponíveis:

* Cota (nível do rio)
* Vazão
* Precipitação
* Metadados das estações

---

## 🗺️ 4. Municípios do Pantanal Considerados

### 📍 Mato Grosso (MT) — 7 municípios

* Barão de Melgaço (MT)
* Cáceres (MT)
* Lambari d’Oeste (MT)
* Poconé (MT)
* Nossa Senhora do Livramento (MT)
* Santo Antônio do Leverger (MT)
* Itiquira (MT)

---

### 📍 Mato Grosso do Sul (MS) — 9 municípios

* Corumbá (MS) — “Capital do Pantanal”
* Ladário (MS)
* Aquidauana (MS)
* Miranda (MS)
* Bodoquena (MS)
* Porto Murtinho (MS)
* Rio Verde de Mato Grosso (MS)
* Sonora (MS)
* Coxim (MS)

---

### 📊 Total

* **16 municípios**
* **7 em MT**
* **9 em MS**

Municípios com maior área inserida no Pantanal:

* **Barão de Melgaço (MT)**
* **Corumbá (MS)**

---

# 🧠 5. Arquitetura Analítica do Projeto

---

## 5.1 Coleta Automatizada (HydroBR)

### ✔ Seleção de estações

* Estados: MT e MS
* Filtro por estações com longas séries históricas
* Download automatizado

### ✔ Consolidação

* DataFrame unificado
* Index temporal padronizado

---

## 5.2 Pré-processamento

### 🔹 Tratamento de Dados

* Interpolação temporal
* Remoção de outliers (IQR / Z-score)
* Verificação de consistência temporal

### 🔹 Engenharia de Variáveis

* Anomalias hidrológicas
* Médias móveis
* Índice padronizado (z-score)
* Classificação automática:

  * Cheia extrema
  * Cheia moderada
  * Normal
  * Seca
  * Seca extrema

---

## 5.3 Análise Exploratória (EDA)

### 📊 Estatísticas Descritivas

* Média
* Desvio padrão
* Assimetria
* Quantis extremos

### 📈 Visualização Temporal

* Séries históricas completas
* Zoom por décadas
* Heatmap anual

### 🔄 Autocorrelação

* ACF
* PACF

### 📉 Decomposição

STL Decomposition:

* Tendência
* Sazonalidade
* Resíduo

---

## 5.4 Extração de Ciclos – Análise Espectral

### 🎵 Transformada de Fourier (FFT)

Aplicação:

[
FFT(x_t)
]

### Objetivos:

* Detectar periodicidades dominantes (ex: 12 meses)
* Identificar ciclos interanuais
* Avaliar mudanças na frequência dominante ao longo das décadas

### Técnicas:

* Periodograma
* Densidade espectral
* Filtro passa-banda
* Wavelet (opcional avançado)

---

## 5.5 Modelagem de Séries Temporais

### 📌 Modelos Estatísticos

* ARIMA
* SARIMA
* SARIMAX (precipitação como variável exógena)

### Avaliação:

* AIC
* BIC
* RMSE
* Cross-validation temporal

---

### 🤖 Modelos de Deep Learning

* LSTM
* Transformer Temporal (Time Series Transformer)

### Objetivos:

* Previsão de cheias futuras
* Antecipação de eventos extremos
* Comparação com modelos clássicos

---

## 5.6 Detecção de Eventos Extremos

### Critérios:

* Percentil 90–95 → Cheia
* Percentil 5–10 → Seca
* Duração mínima consecutiva
* Intensidade acumulada

### Visualizações:

* Gráfico tipo Gantt
* Curvas de severidade
* Ranking de eventos históricos

---

## 5.7 Análise de Tendência

* Teste de Mann-Kendall
* Regressão linear robusta
* Theil-Sen
* Change Point Detection

### Objetivos:

* Detectar intensificação de secas
* Avaliar aumento da variabilidade
* Identificar alterações no regime sazonal

---

## 5.8 Visualização Interativa

### 📍 Mapas

* Mapa interativo das estações
* Classificação por intensidade
* Timeline animada

### Ferramentas:

* Folium
* Plotly
* GeoPandas

---

## 5.9 Exportação

* Exportação automática em Excel (.xlsx)
* CSV
* Relatório PDF
* Download direto no Colab

---

# 📂 6. Estrutura do Notebook no Google Colab

```
01 - Instalação de Pacotes
02 - Coleta de Dados (HydroBR)
03 - Pré-processamento
04 - EDA
05 - Análise Espectral (FFT)
06 - Modelagem SARIMA
07 - Modelagem LSTM / Transformer
08 - Detecção de Eventos Extremos
09 - Mapas Interativos
10 - Exportação de Resultados
```

---

# 📈 7. Resultados Esperados

* ✔ Periodicidade dominante dos ciclos
* ✔ Identificação de ciclos interanuais
* ✔ Quantificação da duração média das cheias
* ✔ Tendência estatisticamente significativa (ou não)
* ✔ Modelo preditivo funcional
* ✔ Dashboard interativo
* ✔ Base exportável para análise externa

---

# 🔬 8. Diferenciais Científicos

* Integração entre hidrologia e ciência de dados
* Uso combinado de FFT + SARIMA + Transformers
* Detecção automática de eventos extremos
* Análise multiescalar (dias, meses, anos)
* Pipeline totalmente reprodutível

---

# 📚 9. Referências Técnicas

* HydroBR (GitHub)
* Box & Jenkins — Modelagem de Séries Temporais
* Análise Espectral em Hidrologia
* Deep Learning aplicado a séries temporais
"""

# 01 — Instalação de Pacotes

!pip install hydrobr
!pip install statsmodels
!pip install pmdarima
!pip install ruptures
!pip install pymannkendall
!pip install plotly
!pip install folium
!pip install geopandas
!pip install openpyxl
!pip install tensorflow

# ================================================================
# Projeto Pantanal - Pipeline Integrado (PLU + FLU)
# ================================================================

# 0) Instalação de pacotes
# !pip install -q hydrobr pymannkendall statsmodels openpyxl tqdm seaborn

# 1) Imports
import os, unicodedata, warnings, time
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm

import pymannkendall as mk
from statsmodels.tsa.seasonal import STL

import hydrobr
from hydrobr import get_data

plt.style.use("seaborn-v0_8-whitegrid")

# 2) Diretórios de saída
OUTDIR_PLU = "/content/pantanal_output"
OUTDIR_FLU = "/content/pantanal_flu_output"
os.makedirs(OUTDIR_PLU, exist_ok=True)
os.makedirs(OUTDIR_FLU, exist_ok=True)

# 3) Lista dos municípios pantaneiros
municipios_pantanal = [
    "BARÃO DE MELGAÇO","CÁCERES","LAMBARI D’OESTE","POCONÉ",
    "NOSSA SENHORA DO LIVRAMENTO","SANTO ANTÔNIO DO LEVERGER","ITIQUIRA",
    "CORUMBÁ","LADÁRIO","AQUIDAUANA","MIRANDA","BODOQUENA",
    "PORTO MURTINHO","RIO VERDE DE MATO GROSSO","SONORA","COXIM"
]

def normalize_txt(s):
    if pd.isna(s): return s
    s = str(s).upper()
    s = unicodedata.normalize('NFKD', s).encode('ascii', errors='ignore').decode('utf-8')
    return s

municipios_norm = [normalize_txt(m) for m in municipios_pantanal]

# BLOCO 1 - PRECIPITAÇÃO (PLU)

print("📥 Baixando inventário de estações PLU...")
inv_plu = get_data.ANA.list_prec_stations(source='ANAF')
inv_plu["City_norm"] = inv_plu["City"].apply(normalize_txt)
plu_pantanal = inv_plu[ inv_plu["City_norm"].isin(municipios_norm) ].copy()
plu_pantanal.to_csv(os.path.join(OUTDIR_PLU, "inventario_PLU_pantanal.csv"), index=False)

codes_plu = plu_pantanal["Code"].astype(str).unique().tolist()

def baixar_prec_wide(codigos, chunk_size=30, pausa=0.3):
    df_all = pd.DataFrame()
    for i in tqdm(range(0, len(codigos), chunk_size), desc="Baixando PLU"):
        bloco = codigos[i:i+chunk_size]
        try:
            df_chunk = get_data.ANA.prec_data(bloco, only_consisted=False)
            df_chunk.index = pd.to_datetime(df_chunk.index, errors="coerce")
            df_chunk = df_chunk[~df_chunk.index.isna()].sort_index()
            df_all = pd.concat([df_all, df_chunk], axis=1)
            time.sleep(pausa)
        except Exception as e:
            print(f"[AVISO] Falha no lote {bloco[:3]}...: {e}")
    return df_all

df_plu = baixar_prec_wide(codes_plu)

def analisar_prec(serie):
    serie = pd.to_numeric(serie, errors="coerce").asfreq("D")
    mensal = serie.resample("M").sum(min_count=1).dropna()
    if mensal.shape[0] < 24: return None
    stl = STL(mensal, period=12, robust=True).fit()
    mkres = mk.original_test(mensal.values)
    return {"inicio":str(mensal.index.min().date()),"fim":str(mensal.index.max().date()),
            "n_obs_mensal":mensal.shape[0],"tendencia_MK":mkres.trend,
            "p_valor_MK":mkres.p,"slope_sen":getattr(mkres,"slope",None)}

metricas_plu = []
for cod in tqdm(df_plu.columns, desc="Analisando PLU"):
    met = analisar_prec(df_plu[cod])
    if met: met.update({"codigo":cod,"tipo":"PLU"}); metricas_plu.append(met)


# BLOCO 2 - FLUVIOMETRIA (VAZÃO + NÍVEL)

print("📥 Baixando inventário de estações FLU...")
inv_flu = get_data.ANA.list_flow_stations(source='ANAF')
inv_flu["City_norm"] = inv_flu["City"].apply(normalize_txt)
flu_pantanal = inv_flu[ inv_flu["City_norm"].isin(municipios_norm) ].copy()
flu_pantanal.to_csv(os.path.join(OUTDIR_FLU, "inventario_FLU_pantanal.csv"), index=False)

codes_flu = flu_pantanal["Code"].astype(str).unique().tolist()

def baixar_flu(codigos, tipo="flow", chunk_size=30, pausa=0.3):
    fn = get_data.ANA.flow_data if tipo=="flow" else get_data.ANA.stage_data
    df_all = pd.DataFrame()
    for i in tqdm(range(0, len(codigos), chunk_size), desc=f"Baixando {tipo.upper()}"):
        bloco = codigos[i:i+chunk_size]
        try:
            df_chunk = fn(bloco, only_consisted=False)
            df_chunk.index = pd.to_datetime(df_chunk.index, errors="coerce")
            df_chunk = df_chunk[~df_chunk.index.isna()].sort_index()
            df_all = pd.concat([df_all, df_chunk], axis=1)
            time.sleep(pausa)
        except Exception as e:
            print(f"[AVISO] Falha no lote {bloco[:3]}...: {e}")
    return df_all

df_flow = baixar_flu(codes_flu, tipo="flow")
df_stage = baixar_flu(codes_flu, tipo="stage")

def analisar_flu(serie):
    serie = pd.to_numeric(serie, errors="coerce").asfreq("D")
    mensal = serie.resample("M").mean().dropna()
    if mensal.shape[0] < 24: return None
    stl = STL(mensal, period=12, robust=True).fit()
    mkres = mk.original_test(mensal.values)
    return {"inicio":str(mensal.index.min().date()),"fim":str(mensal.index.max().date()),
            "n_obs_mensal":mensal.shape[0],"tendencia_MK":mkres.trend,
            "p_valor_MK":mkres.p,"slope_sen":getattr(mkres,"slope",None)}

metricas_flu = []
for cod in tqdm(df_flow.columns, desc="Analisando VAZÃO"):
    met = analisar_flu(df_flow[cod])
    if met: met.update({"codigo":cod,"tipo":"VAZAO"}); metricas_flu.append(met)

for cod in tqdm(df_stage.columns, desc="Analisando NÍVEL"):
    met = analisar_flu(df_stage[cod])
    if met: met.update({"codigo":cod,"tipo":"NIVEL"}); metricas_flu.append(met)


# BLOCO 3 - CONSOLIDAÇÃO FINAL

df_resumo = pd.DataFrame(metricas_plu + metricas_flu)
xls_out = "/content/Resumo_MK_STL_Pantanal.xlsx"
df_resumo.to_excel(xls_out, index=False, engine="openpyxl")
print(f"✅ Relatório consolidado salvo: {xls_out}")

import pandas as pd

# Carrega o arquivo gerado
xls_out = "/content/Resumo_MK_STL_Pantanal.xlsx"
df_resumo = pd.read_excel(xls_out)

# Mostra as primeiras linhas
df_resumo.head()

# Quantidade de série analisadas
df_resumo["tipo"].value_counts()

# Filtrar só tendências decrescentes (ex.: queda de vazão):
df_resumo[ df_resumo["tendencia_MK"] == "decreasing" ]

# Tendências de Crescimento
df_resumo[ df_resumo["tendencia_MK"] == "increasing" ]

# Sem Tendências
df_resumo[ df_resumo["tendencia_MK"] == "no trend" ]

# Resumo estatístico dos slopes (inclinação Sen):
df_resumo.groupby("tipo")["slope_sen"].describe()

# Visualizar distribuição de p‑valores:
import matplotlib.pyplot as plt

plt.hist(df_resumo["p_valor_MK"], bins=20, color="skyblue", edgecolor="black")
plt.title("Distribuição dos p-valores (Mann-Kendall)")
plt.xlabel("p-valor")
plt.ylabel("Frequência")
plt.show()

# Abrir e visualizar os resultados do Resumo_MK_STL_Pantanal.xlsx com alguns gráficos de tendência por município.
import pandas as pd
import matplotlib.pyplot as plt

# Carrega o arquivo consolidado
xls_out = "/content/Resumo_MK_STL_Pantanal.xlsx"
df_resumo = pd.read_excel(xls_out)

# Mostra as primeiras linhas
df_resumo.head()

# Gráfico de tendências por município
# Aqui vamos separar por tipo (PLU = chuva, VAZÃO, NÍVEL) e mostrar a inclinação Sen (slope).
import seaborn as sns

plt.figure(figsize=(12,6))
sns.barplot(data=df_resumo, x="codigo", y="slope_sen", hue="tipo")
plt.xticks(rotation=90)
plt.title("Inclinação Sen por estação (chuva, vazão e nível)")
plt.ylabel("Slope Sen (tendência)")
plt.xlabel("Código da estação")
plt.legend(title="Tipo")
plt.show()

# Tendência por município
# Se quiser agrupar por cidade:

# Junta inventário com resultados
df_resumo["municipio"] = df_resumo["codigo"].map(lambda x: str(x))  # aqui você pode cruzar com inventário PLU/FLU

plt.figure(figsize=(12,6))
sns.countplot(data=df_resumo, x="municipio", hue="tendencia_MK")
plt.xticks(rotation=90)
plt.title("Tendência Mann-Kendall por município")
plt.ylabel("Número de séries")
plt.xlabel("Município")
plt.legend(title="Tendência")
plt.show()

# visualização espacial das estações.
# Mapa interativo do Pantanal.
# Ao clicar no ponto, aparece município, tipo (chuva, vazão, nível) e tendência.
# Cada estação marcada com uma cor:
# Verde → tendência crescente
# Vermelho → tendência decrescente
# Azul → estável

!pip install folium

import folium
import pandas as pd

# Carrega o resumo
xls_out = "/content/Resumo_MK_STL_Pantanal.xlsx"
df_resumo = pd.read_excel(xls_out)

# Exemplo: se o inventário PLU/FLU tiver colunas de latitude/longitude
# (normalmente "Lat" e "Lon"), podemos juntar com o resumo
# Aqui vou supor que você já tem inventário salvo em CSV
inv_plu = pd.read_csv("/content/pantanal_output/inventario_PLU_pantanal.csv")
inv_flu = pd.read_csv("/content/pantanal_flu_output/inventario_FLU_pantanal.csv")

# Junta inventários
inv_total = pd.concat([inv_plu, inv_flu], ignore_index=True)

# Normaliza código para cruzar com df_resumo
inv_total["Code"] = inv_total["Code"].astype(str)
df_resumo["codigo"] = df_resumo["codigo"].astype(str)

# Faz merge para trazer lat/lon
df_mapa = df_resumo.merge(inv_total, left_on="codigo", right_on="Code", how="left")

# Cria mapa centralizado no Pantanal
mapa = folium.Map(location=[-17.5, -57.0], zoom_start=6)

# Adiciona marcadores
for _, row in df_mapa.iterrows():
    if pd.notna(row.get("Lat")) and pd.notna(row.get("Lon")):
        cor = "green" if row["tendencia_MK"]=="increasing" else "red" if row["tendencia_MK"]=="decreasing" else "blue"
        folium.CircleMarker(
            location=[row["Lat"], row["Lon"]],
            radius=6,
            color=cor,
            fill=True,
            fill_color=cor,
            popup=f"{row['City']} - {row['tipo']} ({row['tendencia_MK']})"
        ).add_to(mapa)

mapa

# Exporta o mapa para HTML
mapa.save("/content/mapa_pantanal.html")

# Exporta o mapa para HTML
from google.colab import files
files.download("/content/mapa_pantanal.html")

# Gráfico de tendências por município (usando nomes das cidades)
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))
sns.barplot(data=df_mapa, x="City", y="slope_sen", hue="tipo")
plt.xticks(rotation=90)
plt.title("Inclinação Sen por município (chuva, vazão e nível)")
plt.ylabel("Slope Sen (tendência)")
plt.xlabel("Município")
plt.legend(title="Tipo")
plt.show()

# Tendência por município (Mann-Kendall)
plt.figure(figsize=(12,6))
sns.countplot(data=df_mapa, x="City", hue="tendencia_MK")
plt.xticks(rotation=90)
plt.title("Tendência Mann-Kendall por município")
plt.ylabel("Número de séries")
plt.xlabel("Município")
plt.legend(title="Tendência")
plt.show()

# Inclinação Sen por município (ordenado pelo slope)
import seaborn as sns
import matplotlib.pyplot as plt

# Ordena os municípios pela média do slope
ordem_municipios = (
    df_mapa.groupby("City")["slope_sen"]
    .mean()
    .sort_values()
    .index
)

plt.figure(figsize=(12,6))
sns.barplot(
    data=df_mapa,
    x="City",
    y="slope_sen",
    hue="tipo",
    order=ordem_municipios
)
plt.xticks(rotation=90)
plt.title("Inclinação Sen por município (chuva, vazão e nível)")
plt.ylabel("Slope Sen (tendência)")
plt.xlabel("Município")
plt.legend(title="Tipo")
plt.show()

# Tendência Mann-Kendall por município (ordenado pela contagem)
# Ordena os municípios pela quantidade de séries
ordem_municipios = (
    df_mapa["City"]
    .value_counts()
    .index
)

plt.figure(figsize=(12,6))
sns.countplot(
    data=df_mapa,
    x="City",
    hue="tendencia_MK",
    order=ordem_municipios
)
plt.xticks(rotation=90)
plt.title("Tendência Mann-Kendall por município")
plt.ylabel("Número de séries")
plt.xlabel("Município")
plt.legend(title="Tendência")
plt.show()

# Inclinação Sen por município (horizontal e ordenado)
import seaborn as sns
import matplotlib.pyplot as plt

# Ordena os municípios pela média do slope
ordem_municipios = (
    df_mapa.groupby("City")["slope_sen"]
    .mean()
    .sort_values()
    .index
)

plt.figure(figsize=(10,8))
sns.barplot(
    data=df_mapa,
    y="City",
    x="slope_sen",
    hue="tipo",
    order=ordem_municipios,
    orient="h"
)
plt.title("Inclinação Sen por município (chuva, vazão e nível)")
plt.xlabel("Slope Sen (tendência)")
plt.ylabel("Município")
plt.legend(title="Tipo", bbox_to_anchor=(1.05, 1), loc="upper left")
plt.show()

# Tendência Mann-Kendall por município (horizontal e ordenado)
# Ordena os municípios pela quantidade de séries
ordem_municipios = (
    df_mapa["City"]
    .value_counts()
    .index
)

plt.figure(figsize=(10,8))
sns.countplot(
    data=df_mapa,
    y="City",
    hue="tendencia_MK",
    order=ordem_municipios,
    orient="h"
)
plt.title("Tendência Mann-Kendall por município")
plt.xlabel("Número de séries")
plt.ylabel("Município")
plt.legend(title="Tendência", bbox_to_anchor=(1.05, 1), loc="upper left")
plt.show()

# Tendência Mann-Kendall por município (gráfico empilhado)
import matplotlib.pyplot as plt

# Conta tendências por município
df_tend = df_mapa.groupby(["City", "tendencia_MK"]).size().unstack(fill_value=0)

# Ordena municípios pela soma total de séries
df_tend = df_tend.loc[df_tend.sum(axis=1).sort_values(ascending=False).index]

# Plota gráfico empilhado
df_tend.plot(kind="barh", stacked=True, figsize=(10,8), colormap="Set2")

plt.title("Tendência Mann-Kendall por município")
plt.xlabel("Número de séries")
plt.ylabel("Município")
plt.legend(title="Tendência", bbox_to_anchor=(1.05, 1), loc="upper left")
plt.show()

# Tendência Mann-Kendall por município (empilhado em porcentagem)
import matplotlib.pyplot as plt

# Conta tendências por município
df_tend = df_mapa.groupby(["City", "tendencia_MK"]).size().unstack(fill_value=0)

# Normaliza para porcentagem (cada município = 100%)
df_tend_percent = df_tend.div(df_tend.sum(axis=1), axis=0) * 100

# Ordena municípios pela soma total de séries (ou pela % de "increasing", se preferir)
df_tend_percent = df_tend_percent.loc[df_tend.sum(axis=1).sort_values(ascending=False).index]

# Plota gráfico empilhado em porcentagem
df_tend_percent.plot(kind="barh", stacked=True, figsize=(10,8), colormap="Set2")

plt.title("Proporção da tendência Mann-Kendall por município")
plt.xlabel("Proporção (%)")
plt.ylabel("Município")
plt.legend(title="Tendência", bbox_to_anchor=(1.05, 1), loc="upper left")
plt.show()

# Heatmap de tendências Mann-Kendall por município
import seaborn as sns
import matplotlib.pyplot as plt

# Conta tendências por município
df_tend = df_mapa.groupby(["City", "tendencia_MK"]).size().unstack(fill_value=0)

# Normaliza para porcentagem (cada município = 100%)
df_tend_percent = df_tend.div(df_tend.sum(axis=1), axis=0) * 100

# Ordena municípios pela soma total de séries
df_tend_percent = df_tend_percent.loc[df_tend.sum(axis=1).sort_values(ascending=False).index]

# Cria heatmap
plt.figure(figsize=(12,8))
sns.heatmap(
    df_tend_percent,
    annot=True, fmt=".1f", cmap="YlGnBu",
    cbar_kws={'label': 'Proporção (%)'}
)

plt.title("Mapa de calor das tendências Mann-Kendall por município")
plt.xlabel("Tendência")
plt.ylabel("Município")
plt.show()

# Cluster Heatmap de tendências Mann-Kendall por município
# Agrupar automaticamente os municípios com padrões de tendência semelhantes, criando dendrogramas que mostram quais cidades
# têm distribuições parecidas de "increasing", "decreasing" e "no trend". Isso ajuda a identificar blocos de municípios com comportamento similar.


import seaborn as sns
import matplotlib.pyplot as plt

# Conta tendências por município
df_tend = df_mapa.groupby(["City", "tendencia_MK"]).size().unstack(fill_value=0)

# Normaliza para porcentagem (cada município = 100%)
df_tend_percent = df_tend.div(df_tend.sum(axis=1), axis=0) * 100

# Cria cluster heatmap
sns.clustermap(
    df_tend_percent,
    cmap="YlGnBu",
    figsize=(12,10),
    annot=True, fmt=".1f",
    cbar_kws={'label': 'Proporção (%)'},
    metric="euclidean",  # distância usada para agrupar
    method="ward"        # método de ligação hierárquica
)

plt.suptitle("Cluster Heatmap das tendências Mann-Kendall por município", y=1.02)
plt.show()

# Cluster Heatmap por tipo de série
# Versão clusterizada separada por tipo de série (chuva, vazão, nível).
import seaborn as sns
import matplotlib.pyplot as plt

# Loop para cada tipo de série
for tipo in df_mapa["tipo"].unique():
    # Filtra apenas o tipo atual
    df_tipo = df_mapa[df_mapa["tipo"] == tipo]

    # Conta tendências por município
    df_tend = df_tipo.groupby(["City", "tendencia_MK"]).size().unstack(fill_value=0)

    # Normaliza para porcentagem
    df_tend_percent = df_tend.div(df_tend.sum(axis=1), axis=0) * 100

    # Cria cluster heatmap
    sns.clustermap(
        df_tend_percent,
        cmap="YlGnBu",
        figsize=(12,10),
        annot=True, fmt=".1f",
        cbar_kws={'label': 'Proporção (%)'},
        metric="euclidean",
        method="ward"
    )

    plt.suptitle(f"Cluster Heatmap das tendências Mann-Kendall por município ({tipo})", y=1.02)
    plt.show()

# Cluster Heatmap comparativo (chuva, vazão e nível)
import seaborn as sns
import matplotlib.pyplot as plt

# Define os tipos de série
tipos = df_mapa["tipo"].unique()

# Cria subplots lado a lado
fig, axes = plt.subplots(1, len(tipos), figsize=(18,8))

for ax, tipo in zip(axes, tipos):
    # Filtra apenas o tipo atual
    df_tipo = df_mapa[df_mapa["tipo"] == tipo]

    # Conta tendências por município
    df_tend = df_tipo.groupby(["City", "tendencia_MK"]).size().unstack(fill_value=0)

    # Normaliza para porcentagem
    df_tend_percent = df_tend.div(df_tend.sum(axis=1), axis=0) * 100

    # Heatmap simples (sem dendrograma, para caber nos subplots)
    sns.heatmap(
        df_tend_percent,
        cmap="YlGnBu",
        annot=True, fmt=".1f",
        cbar_kws={'label': 'Proporção (%)'},
        ax=ax
    )

    ax.set_title(f"Tendências ({tipo})")
    ax.set_xlabel("Tendência")
    ax.set_ylabel("Município")

plt.suptitle("Comparação das tendências Mann-Kendall por município (chuva, vazão e nível)", y=1.02)
plt.tight_layout()
plt.show()

# Cluster Heatmap com dendrograma para cada tipo de série
import seaborn as sns
import matplotlib.pyplot as plt

# Define os tipos de série
tipos = df_mapa["tipo"].unique()

for tipo in tipos:
    # Filtra apenas o tipo atual
    df_tipo = df_mapa[df_mapa["tipo"] == tipo]

    # Conta tendências por município
    df_tend = df_tipo.groupby(["City", "tendencia_MK"]).size().unstack(fill_value=0)

    # Normaliza para porcentagem
    df_tend_percent = df_tend.div(df_tend.sum(axis=1), axis=0) * 100

    # Cria cluster heatmap com dendrograma
    g = sns.clustermap(
        df_tend_percent,
        cmap="YlGnBu",
        figsize=(12,10),
        annot=True, fmt=".1f",
        cbar_kws={'label': 'Proporção (%)'},
        metric="euclidean",
        method="ward"
    )

    # Ajusta título
    plt.suptitle(f"Cluster Heatmap das tendências Mann-Kendall por município ({tipo})", y=1.02)
    plt.show()

# Cluster Heatmap com dendrograma e exportação automática
import seaborn as sns
import matplotlib.pyplot as plt

# Define os tipos de série
tipos = df_mapa["tipo"].unique()

for tipo in tipos:
    # Filtra apenas o tipo atual
    df_tipo = df_mapa[df_mapa["tipo"] == tipo]

    # Conta tendências por município
    df_tend = df_tipo.groupby(["City", "tendencia_MK"]).size().unstack(fill_value=0)

    # Normaliza para porcentagem
    df_tend_percent = df_tend.div(df_tend.sum(axis=1), axis=0) * 100

    # Cria cluster heatmap com dendrograma
    g = sns.clustermap(
        df_tend_percent,
        cmap="YlGnBu",
        figsize=(12,10),
        annot=True, fmt=".1f",
        cbar_kws={'label': 'Proporção (%)'},
        metric="euclidean",
        method="ward"
    )

    # Ajusta título
    plt.suptitle(f"Cluster Heatmap das tendências Mann-Kendall por município ({tipo})", y=1.02)

    # Salva gráfico em PNG
    g.savefig(f"cluster_{tipo}.png")

    # Mostra gráfico
    plt.show()

# Cluster Heatmap com exportação para PNG e PDF
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages

# Define os tipos de série
tipos = df_mapa["tipo"].unique()

# Cria um PDF para salvar todos os gráficos juntos
with PdfPages("cluster_tendencias.pdf") as pdf:
    for tipo in tipos:
        # Filtra apenas o tipo atual
        df_tipo = df_mapa[df_mapa["tipo"] == tipo]

        # Conta tendências por município
        df_tend = df_tipo.groupby(["City", "tendencia_MK"]).size().unstack(fill_value=0)

        # Normaliza para porcentagem
        df_tend_percent = df_tend.div(df_tend.sum(axis=1), axis=0) * 100

        # Cria cluster heatmap com dendrograma
        g = sns.clustermap(
            df_tend_percent,
            cmap="YlGnBu",
            figsize=(12,10),
            annot=True, fmt=".1f",
            cbar_kws={'label': 'Proporção (%)'},
            metric="euclidean",
            method="ward"
        )

        # Ajusta título
        plt.suptitle(f"Cluster Heatmap das tendências Mann-Kendall por município ({tipo})", y=1.02)

        # Salva gráfico em PNG
        g.savefig(f"cluster_{tipo}.png")

        # Salva também no PDF
        pdf.savefig(g.fig)

        # Mostra gráfico
        plt.show()

# Diagnóstico - quais códigos não estão sendo associados a municípios e por isso não aparecem nos gráficos.

# Diagnóstico: quantos municípios únicos apareceram
print("Municípios únicos no df_mapa:", df_mapa["City"].nunique())

# Lista todos os municípios encontrados
print("Lista de municípios:", df_mapa["City"].unique())

# Verifica se há códigos sem correspondência
df_sem_city = df_mapa[df_mapa["City"].isna()]
print("Códigos sem município:", df_sem_city["codigo"].unique())

# Correção: padroniza códigos e preenche valores nulos
inv_total["Code"] = inv_total["Code"].astype(str).str.strip().str.zfill(5)
df_resumo["codigo"] = df_resumo["codigo"].astype(str).str.strip().str.zfill(5)

# Atualiza df_mapa com merge corrigido
df_mapa = df_resumo.merge(inv_total, left_on="codigo", right_on="Code", how="left")

# Preenche municípios faltantes com 'Desconhecido'
df_mapa["City"] = df_mapa["City"].fillna("Desconhecido")

# Verifica novamente
print("Municípios únicos após correção:", df_mapa["City"].nunique())

# Tabela resumo: número de séries por município
tabela_resumo = (
    df_mapa.groupby("City")["codigo"]
    .count()
    .reset_index()
    .rename(columns={"codigo": "num_series"})
    .sort_values(by="num_series", ascending=False)
)

print(tabela_resumo)

# Se quiser visualizar como gráfico de barras horizontal
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))
sns.barplot(
    data=tabela_resumo,
    y="City",
    x="num_series",
    orient="h",
    palette="viridis"
)
plt.title("Número de séries por município")
plt.xlabel("Número de séries")
plt.ylabel("Município")
plt.show()

# Lambari D’Oeste, Nossa Senhora do Livramento, Santo Antônio do Leverger, Bodoquena, Rio Verde de Mato Grosso
# podem estar faltando porque o nome no inventário não bate exatamente com o que você está usando no `df_mapa`.
# Busca por parte do nome
# Lista de municípios que você quer garantir
municipios_pantanal = [
    "LAMBARI D’OESTE",
    "NOSSA SENHORA DO LIVRAMENTO",
    "SANTO ANTÔNIO DO LEVERGER",
    "BODOQUENA",
    "RIO VERDE DE MATO GROSSO"
]

# Busca por substring (case insensitive)
for mun in municipios_pantanal:
    encontrados = inv_total[inv_total["City"].str.contains(mun.split()[0], case=False, na=False)]
    print(f"\nBusca por '{mun}':")
    print(encontrados[["Code","City"]])

!pip install fuzzywuzzy[speedup]

# Exemplo com fuzzy match (mais flexível)
# Retorna o município mais parecido no inventário, mesmo que o nome esteja escrito de forma diferente.

from fuzzywuzzy import process

# Lista de todos os municípios do inventário
municipios_lista = inv_total["City"].dropna().unique()

for mun in municipios_pantanal:
    match = process.extractOne(mun, municipios_lista)
    print(f"{mun} -> {match}")

#Substituição
df_mapa["City"] = df_mapa["City"].replace({
    "Lambari D'Oeste": "LAMBARI D’OESTE",
    "N. Sra do Livramento": "NOSSA SENHORA DO LIVRAMENTO",
    "Santo Antonio do Leverger": "SANTO ANTÔNIO DO LEVERGER",
    "Bodoquena": "BODOQUENA",
    "Rio Verde": "RIO VERDE DE MATO GROSSO"
})

# Busca por partes dos nomes
municipios_pantanal = [
    "LAMBARI",
    "LIVRAMENTO",
    "LEVERGER",
    "BODOQUENA",
    "RIO VERDE"
]

for mun in municipios_pantanal:
    encontrados = inv_total[inv_total["City"].str.contains(mun, case=False, na=False)]
    print(f"\nBusca por '{mun}':")
    print(encontrados[["Code","City"]])

# script automático que busca os municípios faltantes por parte do nome e já sugere substituições para padronizar.
# Assim você garante que todos os 16 municípios apareçam corretamente no df_mapa.
# Lista de municípios que você quer garantir LAMBARI D’OESTE, NOSSA SENHORA DO LIVRAMENTO,SANTO ANTÔNIO DO LEVERGER,BODOQUENA e RIO VERDE DE MATO GROSSO

municipios_pantanal = [
    "BARÃO DE MELGAÇO","CÁCERES","LAMBARI D’OESTE","POCONÉ",
    "NOSSA SENHORA DO LIVRAMENTO","SANTO ANTÔNIO DO LEVERGER","ITIQUIRA",
    "CORUMBÁ","LADÁRIO","AQUIDAUANA","MIRANDA","BODOQUENA",
    "PORTO MURTINHO","RIO VERDE DE MATO GROSSO","SONORA","COXIM"
]

# Dicionário para armazenar correspondências encontradas
substituicoes = {}

# Busca por parte do nome (case insensitive)
for mun in municipios_pantanal:
    encontrados = inv_total[inv_total["City"].str.contains(mun.split()[0], case=False, na=False)]
    print(f"\nBusca por '{mun}':")
    print(encontrados[["Code","City"]])

    # Se encontrou algo, pega o primeiro nome e sugere substituição
    if not encontrados.empty:
        nome_inventario = encontrados.iloc[0]["City"]
        substituicoes[nome_inventario] = mun

# Mostra dicionário de substituições sugerido
print("\nDicionário de substituições sugerido:")
print(substituicoes)

# Aplica substituições no df_mapa
df_mapa["City"] = df_mapa["City"].replace(substituicoes)

# Verifica novamente os municípios únicos
print("\nMunicípios únicos após substituição:", df_mapa["City"].nunique())
print(df_mapa["City"].unique())

# Script completo: busca parcial + substituição + relatório em CSV

import pandas as pd

# Lista de municípios que você quer garantir
municipios_pantanal = [
    "BARÃO DE MELGAÇO","CÁCERES","LAMBARI D’OESTE","POCONÉ",
    "NOSSA SENHORA DO LIVRAMENTO","SANTO ANTÔNIO DO LEVERGER","ITIQUIRA",
    "CORUMBÁ","LADÁRIO","AQUIDAUANA","MIRANDA","BODOQUENA",
    "PORTO MURTINHO","RIO VERDE DE MATO GROSSO","SONORA","COXIM"
]

# Dicionário para armazenar correspondências encontradas
substituicoes = {}
relatorio = []

# Busca por parte do nome (case insensitive)
for mun in municipios_pantanal:
    encontrados = inv_total[inv_total["City"].str.contains(mun.split()[0], case=False, na=False)]

    if not encontrados.empty:
        # Pega o primeiro resultado como correspondência
        nome_inventario = encontrados.iloc[0]["City"]
        codigo = encontrados.iloc[0]["Code"]

        # Cria substituição
        substituicoes[nome_inventario] = mun

        # Adiciona ao relatório
        relatorio.append({
            "Nome inventário": nome_inventario,
            "Nome padronizado": mun,
            "Código": codigo
        })
    else:
        # Caso não encontre nada
        relatorio.append({
            "Nome inventário": "NÃO ENCONTRADO",
            "Nome padronizado": mun,
            "Código": "-"
        })

# Aplica substituições no df_mapa
df_mapa["City"] = df_mapa["City"].replace(substituicoes)

# Cria DataFrame do relatório
df_relatorio = pd.DataFrame(relatorio)

# Mostra relatório
print(df_relatorio)

# Exporta para CSV
df_relatorio.to_csv("relatorio_municipios.csv", index=False, encoding="utf-8-sig")

print("\nRelatório exportado para 'relatorio_municipios.csv'")

# Script completo: busca parcial + substituição + relatório com número de séries + exportação CSV
import pandas as pd

# Lista de municípios que você quer garantir
municipios_pantanal = [
    "BARÃO DE MELGAÇO","CÁCERES","LAMBARI D’OESTE","POCONÉ",
    "NOSSA SENHORA DO LIVRAMENTO","SANTO ANTÔNIO DO LEVERGER","ITIQUIRA",
    "CORUMBÁ","LADÁRIO","AQUIDAUANA","MIRANDA","BODOQUENA",
    "PORTO MURTINHO","RIO VERDE DE MATO GROSSO","SONORA","COXIM"
]

# Dicionário para armazenar correspondências encontradas
substituicoes = {}
relatorio = []

# Busca por parte do nome (case insensitive)
for mun in municipios_pantanal:
    encontrados = inv_total[inv_total["City"].str.contains(mun.split()[0], case=False, na=False)]

    if not encontrados.empty:
        # Pega o primeiro resultado como correspondência
        nome_inventario = encontrados.iloc[0]["City"]
        codigo = encontrados.iloc[0]["Code"]

        # Cria substituição
        substituicoes[nome_inventario] = mun

        # Conta quantas séries esse município tem no df_mapa
        num_series = df_mapa[df_mapa["City"] == nome_inventario].shape[0]

        # Adiciona ao relatório
        relatorio.append({
            "Nome inventário": nome_inventario,
            "Nome padronizado": mun,
            "Código": codigo,
            "Número de séries": num_series
        })
    else:
        # Caso não encontre nada
        relatorio.append({
            "Nome inventário": "NÃO ENCONTRADO",
            "Nome padronizado": mun,
            "Código": "-",
            "Número de séries": 0
        })

# Aplica substituições no df_mapa
df_mapa["City"] = df_mapa["City"].replace(substituicoes)

# Cria DataFrame do relatório
df_relatorio = pd.DataFrame(relatorio)

# Mostra relatório
print(df_relatorio)

# Exporta para CSV
df_relatorio.to_csv("relatorio_municipios_num_serie.csv", index=False, encoding="utf-8-sig")

print("\nRelatório exportado para 'relatorio_municipios_num_serie.csv'")

# Interpolação Temporal
import pandas as pd
import numpy as np

# Criando uma série de exemplo com datas faltantes
datas = pd.date_range("2020-01-01", "2020-01-10", freq="D")
valores = [10, np.nan, 12, np.nan, 15, 16, np.nan, 18, 19, np.nan]

df = pd.DataFrame({"nivel": valores}, index=datas)

print("📉 Série original com valores faltantes:")
print(df)

# Função de interpolação temporal
def interpolar_temporal(df, coluna_valor="nivel", freq="D", metodo="linear"):
    """
    Interpolação temporal para séries hidrológicas.
    """
    df.index = pd.to_datetime(df.index)
    df_resampled = df.resample(freq).mean()
    df_resampled[coluna_valor] = df_resampled[coluna_valor].interpolate(method=metodo)
    df_resampled["interpolado"] = df[coluna_valor].isna().reindex(df_resampled.index, fill_value=False)
    return df_resampled

# Aplicando a função
df_interpolado = interpolar_temporal(df, coluna_valor="nivel", freq="D", metodo="linear")

print("\n✅ Série interpolada:")
print(df_interpolado)

# Código com gráfico comparativo

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Criando uma série de exemplo com datas faltantes
datas = pd.date_range("2020-01-01", "2020-01-10", freq="D")
valores = [10, np.nan, 12, np.nan, 15, 16, np.nan, 18, 19, np.nan]

df = pd.DataFrame({"nivel": valores}, index=datas)

# Função de interpolação temporal
def interpolar_temporal(df, coluna_valor="nivel", freq="D", metodo="linear"):
    df.index = pd.to_datetime(df.index)
    df_resampled = df.resample(freq).mean()
    df_resampled[coluna_valor] = df_resampled[coluna_valor].interpolate(method=metodo)
    df_resampled["interpolado"] = df[coluna_valor].isna().reindex(df_resampled.index, fill_value=False)
    return df_resampled

# Aplicando a função
df_interpolado = interpolar_temporal(df, coluna_valor="nivel", freq="D", metodo="linear")

# 🔹 Gráfico comparativo
plt.figure(figsize=(10,5))
plt.plot(df.index, df["nivel"], "o-", label="Original (com NaN)", color="blue")
plt.plot(df_interpolado.index, df_interpolado["nivel"], "o-", label="Interpolada", color="orange")

# Destacar pontos interpolados
plt.scatter(df_interpolado.index[df_interpolado["interpolado"]],
            df_interpolado["nivel"][df_interpolado["interpolado"]],
            color="red", marker="x", s=100, label="Valores interpolados")

plt.title("Interpolação Temporal - Série Hidrológica")
plt.xlabel("Data")
plt.ylabel("Nível")
plt.legend()
plt.grid(True)
plt.show()

# Código comparativo de métodos de interpolação
# Deixar o código comparativo funcionando com linear, nearest e polynomial (order=2):

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Criando uma série de exemplo com datas faltantes
datas = pd.date_range("2020-01-01", "2020-01-10", freq="D")
valores = [10, np.nan, 12, np.nan, 15, 16, np.nan, 18, 19, np.nan]
df = pd.DataFrame({"nivel": valores}, index=datas)

# Função de interpolação temporal
def interpolar_temporal(df, coluna_valor="nivel", freq="D", metodo="linear", order=None):
    df.index = pd.to_datetime(df.index)
    df_resampled = df.resample(freq).mean()
    if order:
        df_resampled[coluna_valor] = df_resampled[coluna_valor].interpolate(method=metodo, order=order)
    else:
        df_resampled[coluna_valor] = df_resampled[coluna_valor].interpolate(method=metodo)
    return df_resampled

# Aplicando diferentes métodos
df_linear = interpolar_temporal(df, metodo="linear")
df_nearest = interpolar_temporal(df, metodo="nearest")
df_polynomial = interpolar_temporal(df, metodo="polynomial", order=2)  # ordem polinomial definida

# Gráfico comparativo
plt.figure(figsize=(12,6))

plt.plot(df.index, df["nivel"], "o-", label="Original (com NaN)", color="blue")
plt.plot(df_linear.index, df_linear["nivel"], "o-", label="Linear", color="orange")
plt.plot(df_nearest.index, df_nearest["nivel"], "o-", label="Nearest", color="green")
plt.plot(df_polynomial.index, df_polynomial["nivel"], "o-", label="Polynomial (ordem=2)", color="red")

plt.title("Comparação de Métodos de Interpolação")
plt.xlabel("Data")
plt.ylabel("Nível")
plt.legend()
plt.grid(True)
plt.show()

# Código com RMSE e MAE
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Criando série de exemplo com valores faltantes
datas = pd.date_range("2020-01-01", "2020-01-10", freq="D")
valores = [10, np.nan, 12, np.nan, 15, 16, np.nan, 18, 19, np.nan]
df = pd.DataFrame({"nivel": valores}, index=datas)

# Função de interpolação temporal
def interpolar_temporal(df, coluna_valor="nivel", freq="D", metodo="linear", order=None):
    df.index = pd.to_datetime(df.index)
    df_resampled = df.resample(freq).mean()
    if order:
        df_resampled[coluna_valor] = df_resampled[coluna_valor].interpolate(method=metodo, order=order)
    else:
        df_resampled[coluna_valor] = df_resampled[coluna_valor].interpolate(method=metodo)
    return df_resampled

# Aplicando diferentes métodos
df_linear = interpolar_temporal(df, metodo="linear")
df_nearest = interpolar_temporal(df, metodo="nearest")
df_polynomial = interpolar_temporal(df, metodo="polynomial", order=2)

#  Gráfico comparativo
plt.figure(figsize=(12,6))
plt.plot(df.index, df["nivel"], "o-", label="Original (com NaN)", color="blue")
plt.plot(df_linear.index, df_linear["nivel"], "o-", label="Linear", color="orange")
plt.plot(df_nearest.index, df_nearest["nivel"], "o-", label="Nearest", color="green")
plt.plot(df_polynomial.index, df_polynomial["nivel"], "o-", label="Polynomial (ordem=2)", color="red")
plt.title("Comparação de Métodos de Interpolação")
plt.xlabel("Data")
plt.ylabel("Nível")
plt.legend()
plt.grid(True)
plt.show()

# Avaliação quantitativa
# Usamos apenas os pontos originais não nulos como referência
mask = ~df["nivel"].isna()
y_true = df["nivel"][mask]

# Extraímos os valores interpolados correspondentes
y_linear = df_linear["nivel"][mask]
y_nearest = df_nearest["nivel"][mask]
y_poly = df_polynomial["nivel"][mask]

# Calculamos métricas
def avaliar(y_true, y_pred, metodo):
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mae = mean_absolute_error(y_true, y_pred)
    print(f"{metodo}: RMSE={rmse:.3f}, MAE={mae:.3f}")

avaliar(y_true, y_linear, "Linear")
avaliar(y_true, y_nearest, "Nearest")
avaliar(y_true, y_poly, "Polynomial (ordem=2)")

#Código para múltiplas estações

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error, mean_absolute_error
import os

# Função de interpolação temporal
def interpolar_temporal(df, coluna_valor="nivel", freq="D", metodo="linear", order=None):
    df.index = pd.to_datetime(df.index)
    df_resampled = df.resample(freq).mean()
    if order:
        df_resampled[coluna_valor] = df_resampled[coluna_valor].interpolate(method=metodo, order=order)
    else:
        df_resampled[coluna_valor] = df_resampled[coluna_valor].interpolate(method=metodo)
    return df_resampled

# Função para avaliar interpolação
def avaliar(y_true, y_pred):
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mae = mean_absolute_error(y_true, y_pred)
    return rmse, mae

#  Pipeline para várias estações
def processar_estacoes(dados_estacoes, coluna_valor="nivel", freq="D"):
    os.makedirs("results/interpolacao", exist_ok=True)
    resultados = []

    for nome, df in dados_estacoes.items():
        print(f"Processando estação: {nome}")

        # Aplicar métodos
        df_linear = interpolar_temporal(df, coluna_valor=coluna_valor, freq=freq, metodo="linear")
        df_nearest = interpolar_temporal(df, coluna_valor=coluna_valor, freq=freq, metodo="nearest")
        df_poly = interpolar_temporal(df, coluna_valor=coluna_valor, freq=freq, metodo="polynomial", order=2)

        # Gráfico comparativo
        plt.figure(figsize=(12,6))
        plt.plot(df.index, df[coluna_valor], "o-", label="Original", color="blue")
        plt.plot(df_linear.index, df_linear[coluna_valor], "o-", label="Linear", color="orange")
        plt.plot(df_nearest.index, df_nearest[coluna_valor], "o-", label="Nearest", color="green")
        plt.plot(df_poly.index, df_poly[coluna_valor], "o-", label="Polynomial (ordem=2)", color="red")
        plt.title(f"Interpolação Temporal - Estação {nome}")
        plt.xlabel("Data")
        plt.ylabel(coluna_valor)
        plt.legend()
        plt.grid(True)
        plt.savefig(f"results/interpolacao/{nome}_comparacao.png")
        plt.close()

        # Avaliação quantitativa (apenas pontos originais não nulos)
        mask = ~df[coluna_valor].isna()
        y_true = df[coluna_valor][mask]
        y_linear = df_linear[coluna_valor][mask]
        y_nearest = df_nearest[coluna_valor][mask]
        y_poly = df_poly[coluna_valor][mask]

        resultados.append({
            "estacao": nome,
            "RMSE_linear": avaliar(y_true, y_linear)[0],
            "MAE_linear": avaliar(y_true, y_linear)[1],
            "RMSE_nearest": avaliar(y_true, y_nearest)[0],
            "MAE_nearest": avaliar(y_true, y_nearest)[1],
            "RMSE_poly": avaliar(y_true, y_poly)[0],
            "MAE_poly": avaliar(y_true, y_poly)[1],
        })

    # Salvar métricas em CSV
    # Cria DataFrame do relatório

df_relatorio = pd.DataFrame(relatorio)

# Mostra relatório
print(df_relatorio)

# Exporta para CSV
df_relatorio.to_csv("metricas_interpolacao.csv", index=False, encoding="utf-8-sig")

print("\✅ Processamento concluído dos Gráficos e métricas salvos.")

# Exemplo de dados fictícios para duas estações
datas = pd.date_range("2020-01-01", "2020-01-10", freq="D")
valores1 = [10, np.nan, 12, np.nan, 15, 16, np.nan, 18, 19, np.nan]
valores2 = [20, 21, np.nan, 23, np.nan, 25, 26, np.nan, 28, 29]

dados_estacoes = {
    "Estacao_MT_01": pd.DataFrame({"nivel": valores1}, index=datas),
    "Estacao_MS_02": pd.DataFrame({"nivel": valores2}, index=datas)
}

processar_estacoes(dados_estacoes, coluna_valor="nivel", freq="D")

# Leitura do XML https://telemetriaws1.ana.gov.br/ServiceANA.asmx?op=ListaEstacoesTelemetricas

import pandas as pd

# URL do XML no site da ANA
url = "https://telemetriaws1.ana.gov.br/ServiceANA.asmx?op=ListaEstacoesTelemetricas"

# Ler direto do site
df = pd.read_xml(url)

# Separar município e UF
df[["Municipio", "UF"]] = df["Municipio-UF"].str.split("-", expand=True)

# Selecionar colunas de interesse
df_lista = df[["CodEstacao", "NomeEstacao", "Municipio", "UF", "NomeRio"]]

# Salvar em CSV
df_lista.to_csv("lista_estacoes.csv", index=False)

print("✅ Lista salva em 'lista_estacoes.csv'")

##  Passo 1: Ler o TXT
# Mesmo que o arquivo seja XML salvo como `.txt`, o `pandas` consegue interpretar:


import pandas as pd

# Ler o TXT que contém XML
df = pd.read_xml("ListaEstacoesTelemetricas_MS_MT.txt")

# Separar município e UF
df[["Municipio", "UF"]] = df["Municipio-UF"].str.split("-", expand=True)

# Filtrar apenas MT e MS
df_mtms = df[df["UF"].isin(["MT", "MS"])]

# Visualizar primeiras linhas
print(df_mtms.head())

#  Script completo

import pandas as pd

# 1. Ler apenas os elementos <Table> dentro do XML
df = pd.read_xml("ListaEstacoesTelemetricas_MS_MT_v2.txt", xpath="//Table")

# 2. Separar Município e UF
df[["Municipio", "UF"]] = df["Municipio-UF"].str.split("-", expand=True)

# 3. Filtrar apenas MT e MS
df_mtms = df[df["UF"].isin(["MT", "MS"])]

# 4. Reorganizar colunas para facilitar leitura
df_mtms = df_mtms[[
    "CodEstacao",
    "NomeEstacao",
    "Municipio",
    "UF",
    "NomeRio",
    "CodRio",
    "Operadora",
    "Responsavel",
    "Latitude",
    "Longitude",
    "Altitude",
    "Bacia",
    "SubBacia",
    "Origem",
    "StatusEstacao"
]]

# 5. Exportar para Excel
df_mtms.to_excel("Estacoes_MT_MS.xlsx", index=False)

print("Arquivo 'Estacoes_MT_MS.xlsx' gerado com sucesso!")

### Transpor com Pandas Inverter linhas ↔ colunas:


# Transpor o DataFrame filtrado
df_transposto = df_mtms.T

# Exportar para Excel
df_transposto.to_excel("Estacoes_MT_MS_transposto.xlsx", index=True)

import pandas as pd

# 1. Ler apenas os elementos <Table> dentro do XML
df = pd.read_xml("ListaEstacoesTelemetricas_MS_MT_v2.txt", xpath="//Table")

# 2. Separar Município e UF
df[["Municipio", "UF"]] = df["Municipio-UF"].str.split("-", expand=True)

# 3. Filtrar apenas MT e MS
df_mtms = df[df["UF"].isin(["MT", "MS"])]

# 4. Reorganizar colunas para facilitar leitura
df_mtms = df_mtms[[
    "CodEstacao",
    "NomeEstacao",
    "Municipio",
    "UF",
    "NomeRio",
    "CodRio",
    "Operadora",
    "Responsavel",
    "Latitude",
    "Longitude",
    "Altitude",
    "Bacia",
    "SubBacia",
    "Origem",
    "StatusEstacao"
]]

# 5. Exportar versão normal para Excel
df_mtms.to_excel("Estacoes_MT_MS.xlsx", index=False)

# 6. Exportar versão transposta (linhas viram colunas)
df_transposto = df_mtms.T
df_transposto.to_excel("Estacoes_MT_MS_transposto.xlsx", index=True)

print("Arquivos 'Estacoes_MT_MS.xlsx' e 'Estacoes_MT_MS_transposto.xlsx' gerados com sucesso!")

# `XMLSyntaxError: StartTag: invalid element name` acontece porque o arquivo `.txt`
# não está formatado como um XML completo — ele provavelmente começa direto com `<Table>`
# sem um cabeçalho ou uma raiz única. O `pandas.read_xml` exige que o conteúdo seja um XML bem formado.

# Como resolver
# Ler como texto e usar `lxml` ou `BeautifulSoup`

import pandas as pd

# Ler o arquivo como texto
with open("ListaEstacoesTelemetricas_MS_MT_v2.txt", "r", encoding="utf-8") as f:
    xml_content = f.read()

# Adicionar uma raiz artificial
xml_content = "<Root>" + xml_content + "</Root>"

# Ler com pandas
df = pd.read_xml(xml_content, xpath="//Table")

# Separar Município e UF
df[["Municipio", "UF"]] = df["Municipio-UF"].str.split("-", expand=True)

# Filtrar apenas MT e MS
df_mtms = df[df["UF"].isin(["MT", "MS"])]

# Reorganizar colunas
df_mtms = df_mtms[[
    "CodEstacao",
    "NomeEstacao",
    "Municipio",
    "UF",
    "NomeRio",
    "CodRio",
    "Operadora",
    "Responsavel",
    "Latitude",
    "Longitude",
    "Altitude",
    "Bacia",
    "SubBacia",
    "Origem",
    "StatusEstacao"
]]

# Exportar versão normal
df_mtms.to_excel("Estacoes_MT_MS.xlsx", index=False)

# Exportar versão transposta
df_mtms.T.to_excel("Estacoes_MT_MS_transposto.xlsx", index=True)

print("Arquivos gerados com sucesso!")

import pandas as pd
from io import StringIO

# 1. Ler o arquivo como texto
with open("ListaEstacoesTelemetricas_MS_MT_v2.txt", "r", encoding="utf-8") as f:
    xml_content = f.read()

# 2. Adicionar uma raiz artificial <Root> ... </Root>
xml_content = "<Root>" + xml_content + "</Root>"

# 3. Usar StringIO para passar a string como "arquivo"
df = pd.read_xml(StringIO(xml_content), xpath="//Table")

# 4. Separar Município e UF
df[["Municipio", "UF"]] = df["Municipio-UF"].str.split("-", expand=True)

# 5. Filtrar apenas MT e MS
df_mtms = df[df["UF"].isin(["MT", "MS"])]

# 6. Reorganizar colunas
df_mtms = df_mtms[[
    "CodEstacao",
    "NomeEstacao",
    "Municipio",
    "UF",
    "NomeRio",
    "CodRio",
    "Operadora",
    "Responsavel",
    "Latitude",
    "Longitude",
    "Altitude",
    "Bacia",
    "SubBacia",
    "Origem",
    "StatusEstacao"
]]

# 7. Exportar versão normal
df_mtms.to_excel("Estacoes_MT_MS.xlsx", index=False)

# 8. Exportar versão transposta
df_mtms.T.to_excel("Estacoes_MT_MS_transposto.xlsx", index=True)

print("Arquivos 'Estacoes_MT_MS.xlsx' e 'Estacoes_MT_MS_transposto.xlsx' gerados com sucesso!")

# Solução prática
# Em vez de tentar forçar o read_xml, você pode usar o BeautifulSoup ou o lxml.etree para tratar o conteúdo como XML parcial
# e depois converter para DataFrame.

import pandas as pd
from bs4 import BeautifulSoup

# 1. Ler o arquivo como texto
with open("ListaEstacoesTelemetricas_MS_MT_v2.txt", "r", encoding="utf-8") as f:
    xml_content = f.read()

# 2. Adicionar raiz artificial
xml_content = "<Root>" + xml_content + "</Root>"

# 3. Parsear com BeautifulSoup
soup = BeautifulSoup(xml_content, "xml")

# 4. Extrair todas as tags <Table>
tables = soup.find_all("Table")

# 5. Converter cada <Table> em dicionário
data = []
for t in tables:
    row = {}
    for child in t.find_all():
        row[child.name] = child.text.strip()
    data.append(row)

# 6. Criar DataFrame
df = pd.DataFrame(data)

# 7. Separar Município e UF
df[["Municipio", "UF"]] = df["Municipio-UF"].str.split("-", expand=True)

# 8. Filtrar apenas MT e MS
df_mtms = df[df["UF"].isin(["MT", "MS"])]

# 9. Reorganizar colunas
df_mtms = df_mtms[[
    "CodEstacao",
    "NomeEstacao",
    "Municipio",
    "UF",
    "NomeRio",
    "CodRio",
    "Operadora",
    "Responsavel",
    "Latitude",
    "Longitude",
    "Altitude",
    "Bacia",
    "SubBacia",
    "Origem",
    "StatusEstacao"
]]

# 10. Exportar versão normal
df_mtms.to_excel("Estacoes_MT_MS.xlsx", index=False)

# 11. Exportar versão transposta
df_mtms.T.to_excel("Estacoes_MT_MS_transposto.xlsx", index=True)

print("Arquivos 'Estacoes_MT_MS.xlsx' e 'Estacoes_MT_MS_transposto.xlsx' gerados com sucesso!")

# o erro de `KeyError: 'Municipio-UF'` significa que a coluna **não existe** no `DataFrame` que foi montado.
# Isso acontece porque, ao usar o `BeautifulSoup`, os nomes das tags viram os nomes das colunas — e no seu XML a
# tag se chama exatamente `<Municipio-UF>`. O hífen no nome da tag pode estar sendo interpretado de forma diferente ou até removido.

import pandas as pd
from bs4 import BeautifulSoup

# 1. Ler o arquivo como texto
with open("ListaEstacoesTelemetricas_MS_MT_v2.txt", "r", encoding="utf-8") as f:
    xml_content = f.read()

# 2. Adicionar raiz artificial
xml_content = "<Root>" + xml_content + "</Root>"

# 3. Parsear com BeautifulSoup
soup = BeautifulSoup(xml_content, "xml")

# 4. Extrair todas as tags <Table>
tables = soup.find_all("Table")

# 5. Converter cada <Table> em dicionário
data = []
for t in tables:
    row = {}
    for child in t.find_all():
        row[child.name] = child.text.strip()
    data.append(row)

# 6. Criar DataFrame
df = pd.DataFrame(data)

# 👉 Ver quais colunas realmente existem
print("Colunas disponíveis:", df.columns.tolist())

# 7. Se a coluna veio com nome diferente (ex: 'Municipio_UF' ou 'MunicipioUF'), renomear:
df.rename(columns={"Municipio_UF": "Municipio-UF", "MunicipioUF": "Municipio-UF"}, inplace=True)

# 8. Agora separar Município e UF
if "Municipio-UF" in df.columns:
    df[["Municipio", "UF"]] = df["Municipio-UF"].str.split("-", expand=True)
else:
    print("⚠️ A coluna 'Municipio-UF' não foi encontrada. Veja os nomes listados acima.")

# 9. Filtrar apenas MT e MS
if "UF" in df.columns:
    df_mtms = df[df["UF"].isin(["MT", "MS"])]
else:
    df_mtms = df

# 10. Reorganizar colunas
colunas = [
    "CodEstacao","NomeEstacao","Municipio","UF","NomeRio","CodRio",
    "Operadora","Responsavel","Latitude","Longitude","Altitude",
    "Bacia","SubBacia","Origem","StatusEstacao"
]
df_mtms = df_mtms[[c for c in colunas if c in df_mtms.columns]]

# 11. Exportar versão normal
df_mtms.to_excel("Estacoes_MT_MS.xlsx", index=False)

# 12. Exportar versão transposta
df_mtms.T.to_excel("Estacoes_MT_MS_transposto.xlsx", index=True)

print("Arquivos gerados com sucesso!")

print("Colunas disponíveis:", df.columns.tolist())