# -*- coding: utf-8 -*-
"""Cópia de Pantanal_HydroBR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ni1sIFZ5ahkhn-59yqsagaf3kOcbP7_B

#  Projeto de Ciência de Dados

# Modelagem, Detecção e Predição dos Ciclos Hidrológicos do Pantanal

---

##  1. Contextualização

O **Pantanal** é a maior planície alagável tropical do planeta, com regime hidrológico altamente sazonal.

A alternância entre **cheias e secas** impacta:

* 🌱 Biodiversidade
* 🚢 Navegação
* 🌾 Agricultura
* 💧 Segurança hídrica
* 💰 Economia regional

Mudanças recentes levantam hipóteses sobre possível alteração estrutural no regime hidrológico.

---

##  2. Problema de Pesquisa

### Pergunta Central

> Qual é a dinâmica, frequência, intensidade, espacialização e tendência dos ciclos de cheias e secas no Pantanal ao longo das últimas décadas?

### Subquestões

* Há mudança estrutural no regime hidrológico?
* Eventos extremos estão se intensificando?
* É possível prever cheias e secas com modelos estatísticos e Deep Learning?
* Existem padrões distintos entre municípios?

---

##  3. Área de Estudo

###  Mato Grosso (MT)

* Barão de Melgaço
* Cáceres
* Lambari d’Oeste
* Poconé
* Nossa Senhora do Livramento
* Santo Antônio do Leverger
* Itiquira

###  Mato Grosso do Sul (MS)

* Corumbá
* Ladário
* Aquidauana
* Miranda
* Bodoquena
* Porto Murtinho
* Rio Verde de Mato Grosso
* Sonora
* Coxim

### 🔎 Total

* 16 municípios
* 7 em MT
* 9 em MS

Municípios com maior área no Pantanal:

* Barão de Melgaço (MT)
* Corumbá (MS)

---

##  4. Fonte de Dados

Os dados serão obtidos via pacote **HydroBR**, com acesso estruturado às bases da
**Agência Nacional de Águas**.

### Variáveis disponíveis

* Cota (nível do rio)
* Vazão
* Precipitação
* Metadados das estações

### Critérios de seleção

* Estações em MT e MS
* Séries históricas longas
* Consistência temporal

---

#  5. Metodologia Analítica

---

## 5.1 Coleta Automatizada

* Seleção automatizada de estações
* Download programático
* Consolidação em DataFrame único
* Padronização do índice temporal

---

## 5.2 Pré-processamento

### 🔹 Tratamento

* Interpolação temporal
* Remoção de outliers (IQR / Z-score)
* Verificação de consistência

### 🔹 Engenharia de Variáveis

* Anomalias hidrológicas
* Médias móveis
* Padronização (z-score)
* Classificação automática:

| Classe         | Critério       |
| -------------- | -------------- |
| Cheia extrema  | > Percentil 95 |
| Cheia moderada | 90–95          |
| Normal         | 10–90          |
| Seca           | 5–10           |
| Seca extrema   | < 5            |

---

## 5.3 Análise Exploratória (EDA)

### Estatísticas Descritivas

* Média
* Desvio padrão
* Assimetria
* Curtose
* Quantis extremos

### Visualizações

* Séries históricas completas
* Comparação por décadas
* Heatmap anual
* Boxplots sazonais

### Dependência Temporal

* ACF
* PACF

### Decomposição STL

* Tendência
* Sazonalidade
* Resíduo

---

## 5.4 Análise Espectral – Extração de Ciclos

Aplicação da Transformada Rápida de Fourier (FFT):

[
FFT(x_t)
]

### Objetivos

* Identificar periodicidade dominante
* Detectar ciclos interanuais
* Avaliar mudanças na frequência dominante
* Identificar ciclos de seca prolongada

### Técnicas complementares

* Periodograma
* Densidade espectral
* Filtro passa-banda
* Wavelet (análise multiescalar)

---

## 5.5 Modelagem de Séries Temporais

###  Modelos Estatísticos

* ARIMA
* SARIMA
* SARIMAX (com precipitação exógena)

### Métricas

* AIC
* BIC
* RMSE
* Cross-validation temporal

---

###  Modelos de Deep Learning

* LSTM
* Transformer para Séries Temporais

### Objetivos

* Previsão de cheias futuras
* Antecipação de eventos extremos
* Comparação com modelos clássicos

---

## 5.6 Detecção de Eventos Extremos

### Critérios

* Percentil 90–95 → Cheia
* Percentil 5–10 → Seca
* Duração mínima consecutiva
* Intensidade acumulada

### Visualizações

* Gráfico tipo Gantt
* Curvas de severidade
* Ranking histórico

---

## 5.7 Análise de Tendência e Mudança Estrutural

* Teste de Mann-Kendall
* Regressão linear robusta
* Theil-Sen
* Change Point Detection

### Objetivos

* Detectar intensificação de secas
* Avaliar aumento da variabilidade
* Identificar alterações no regime sazonal

---

## 5.8 Visualização Interativa

### Mapas

* Estações georreferenciadas
* Classificação por intensidade
* Timeline animada

### Ferramentas

* Folium
* Plotly
* GeoPandas

---

## 5.9 Exportação

* Excel (.xlsx)
* CSV
* Relatório PDF
* Download direto no Colab

---

#  6. Estrutura do Notebook

```
01 - Instalação de Pacotes
02 - Coleta de Dados
03 - Pré-processamento
04 - Análise Exploratória
05 - Análise Espectral (FFT)
06 - Modelagem SARIMA
07 - Modelagem LSTM / Transformer
08 - Eventos Extremos
09 - Mapas Interativos
10 - Exportação
```

---

#  7. Resultados Esperados

* ✔ Periodicidade dominante dos ciclos
* ✔ Identificação de ciclos interanuais
* ✔ Duração média das cheias
* ✔ Tendência estatisticamente significativa (ou não)
* ✔ Modelo preditivo validado
* ✔ Dashboard interativo
* ✔ Base exportável para pesquisas futuras

---

#  8. Contribuições Científicas

* Integração entre hidrologia e ciência de dados
* FFT + SARIMA + Transformers no mesmo pipeline
* Detecção automática de eventos extremos
* Análise multiescalar (dias, meses, anos)
* Pipeline totalmente reprodutível

## **1️⃣ Instalação de pacotes e configuração inicial**
* `pandas` → manipulação de DataFrames
* `numpy` → operações matemáticas
* `hydrobr.get_data` → pacote que acessa dados da **ANA** (Agência Nacional de Águas)
* `tqdm.notebook` → barra de progresso visual no Colab durante downloads grandes
"""



# Instalação de Bibliotecas
!pip install hydrobr # Acesso e download de dados hidrológicos da ANA (Hidroweb) de forma automatizada
!pip install pymannkendall # Testes estatísticos de tendência em séries temporais (ex.: Mann-Kendall)
!pip install statsmodels #análise estatística avançada e modelagem estatística
!pip install openpyxl #leitura e escrita de arquivos Excel (.xlsx)
!pip install tqdm #barras de progresso para loops e tarefas demoradas
!pip install seaborn #criação de gráficos estatísticos bonitos e simples

# Imports


import pandas as pd
import numpy as np
from hydrobr import get_data
from tqdm.notebook import tqdm

# Lista todas as estações de precipitação disponíveis
lista_estacoes_precipitacao = get_data.ANA.list_prec_stations()
print("Total de estações:", lista_estacoes_precipitacao.shape[0])

# Exibir as 20 primeiras
lista_estacoes_precipitacao.head(20)

cidade = "Campo Grande"
filtro = lista_estacoes_precipitacao[
    lista_estacoes_precipitacao["City"].str.upper() == cidade.upper()
]

print(f"Estações encontradas em {cidade}:")
filtro

cidade_parcial = "Miran"
filtro_parcial = lista_estacoes_precipitacao[
    lista_estacoes_precipitacao["City"].str.contains(cidade_parcial, case=False, na=False)
]

print("Estações com nome que contém:", cidade_parcial)
filtro_parcial

# 2 Coleta de Dados - Lista de municípios do Pantanal e normalização
# Lista oficial de municípios pantaneiros
municipios_pantanal = [
    "BARÃO DE MELGAÇO","CÁCERES","LAMBARI D’OESTE","POCONÉ",
    "NOSSA SENHORA DO LIVRAMENTO","SANTO ANTÔNIO DO LEVERGER","ITIQUIRA",
    "CORUMBÁ","LADÁRIO","AQUIDAUANA","MIRANDA","BODOQUENA",
    "PORTO MURTINHO","RIO VERDE DE MATO GROSSO","SONORA","COXIM",
    # "Porto Esperidião", #vinculada a região Pantaneira
    # "Porto Estrela", #vinculada a região Pantaneira"
]

# Normalizar texto para evitar problemas com acentos e maiúsculas/minúsculas
lista_estacoes_precipitacao["City_norm"] = (
    lista_estacoes_precipitacao["City"]
    .str.upper()
    .str.normalize('NFKD')
    .str.encode('ascii', errors='ignore')
    .str.decode('utf-8')
)

municipios_norm = [
    m.upper().encode('ascii', errors='ignore').decode('utf-8')
    for m in municipios_pantanal
]

# Filtrar apenas as estações do Pantanal
estacoes_pantanal = lista_estacoes_precipitacao[
    lista_estacoes_precipitacao["City_norm"].isin(municipios_norm)
]

print("Estações encontradas nas cidades do Pantanal:", estacoes_pantanal.shape[0])
estacoes_pantanal

# Listar de todos os métodos disponíveis para ANA
dir(get_data.ANA)

# Verificação da documentação dentro do Colab:
help(get_data.ANA)

"""list_flow_stations() é o método correto para listar estações de vazão.

flow_data() recebe uma lista de códigos mesmo que seja só um código por vez.

Normalizamos os nomes das cidades (City_norm) para filtrar apenas os municípios pantaneiros.

Consolidamos todas as séries em um DataFrame único (df_flu_all), pronto para análise.
"""

# -------------------------------
# Importações
# -------------------------------
import pandas as pd
import numpy as np
from hydrobr import get_data
from tqdm.notebook import tqdm
import unicodedata

# -------------------------------
# 1️⃣ Lista oficial de municípios do Pantanal
# -------------------------------
municipios_pantanal = [
    "BARÃO DE MELGAÇO","CÁCERES","LAMBARI D’OESTE","POCONÉ",
    "NOSSA SENHORA DO LIVRAMENTO","SANTO ANTÔNIO DO LEVERGER","ITIQUIRA",
    "CORUMBÁ","LADÁRIO","AQUIDAUANA","MIRANDA","BODOQUENA",
    "PORTO MURTINHO","RIO VERDE DE MATO GROSSO","SONORA","COXIM"
]

# Função de normalização de texto
# def normalize_txt(txt):
#    return txt.upper().normalize('NFKD').encode('ascii', errors='ignore').decode('utf-8')

def normalize_txt(txt):
    # Garantir que txt é string
    txt = str(txt)
    # Normalizar acentos
    txt = unicodedata.normalize('NFKD', txt)
    # Remover caracteres não ASCII e converter para maiúsculas
    txt = txt.encode('ascii', errors='ignore').decode('utf-8').upper()
    return txt


# Normalizar lista de municípios
municipios_norm = [normalize_txt(m) for m in municipios_pantanal]
print(municipios_norm)

# -------------------------------
# 2️⃣ Estações de precipitação
# -------------------------------
lista_prec = get_data.ANA.list_prec_stations()  # todas as estações de precipitação
lista_prec["City_norm"] = lista_prec["City"].apply(normalize_txt)

# Filtrar apenas municípios do Pantanal
estacoes_prec_pantanal = lista_prec[lista_prec["City_norm"].isin(municipios_norm)].copy()
print("Estações de precipitação no Pantanal:", estacoes_prec_pantanal.shape[0])

# Baixar séries de precipitação
dados_prec = {}
for codigo in tqdm(estacoes_prec_pantanal["Code"].astype(str), desc="Baixando precipitação"):
    try:
        df = get_data.ANA.prec_data([codigo], only_consisted=False)  # recebe lista
        df.index = pd.to_datetime(df.index)  # padronizar índice temporal
        dados_prec[codigo] = df
    except Exception as e:
        print(f"Erro ao baixar {codigo}: {e}")

# Consolidar todas as séries em um único DataFrame
df_prec_all = pd.concat(dados_prec.values(), keys=dados_prec.keys(), names=["Code", "Date"])
df_prec_all.reset_index(inplace=True)

# -------------------------------
# 3️⃣ Estações de vazão (flow)
# -------------------------------
lista_flu = get_data.ANA.list_flow_stations()  # método correto
lista_flu["City_norm"] = lista_flu["City"].apply(normalize_txt)

# Filtrar municípios do Pantanal
estacoes_flu_pantanal = lista_flu[lista_flu["City_norm"].isin(municipios_norm)].copy()
codigos_flu = estacoes_flu_pantanal["Code"].astype(str).tolist()
print("Estações de vazão no Pantanal:", len(codigos_flu))

# Baixar séries de vazão
dados_flu = {}
for codigo in tqdm(codigos_flu, desc="Baixando vazão"):
    try:
        df = get_data.ANA.flow_data([codigo], only_consisted=False)  # recebe lista de códigos
        df.index = pd.to_datetime(df.index)
        dados_flu[codigo] = df
    except Exception as e:
        print(f"Erro ao baixar {codigo}: {e}")

# Consolidar em único DataFrame
df_flu_all = pd.concat(dados_flu.values(), keys=dados_flu.keys(), names=["Code", "Date"])
df_flu_all.reset_index(inplace=True)

# -------------------------------
# 4️⃣ Visualização inicial
# -------------------------------
print("Pré-visualização - Precipitação")
display(df_prec_all.head())

print("Pré-visualização - Vazão")
display(df_flu_all.head())

# -------------------------------
# Importações
# -------------------------------
import pandas as pd
import numpy as np
from hydrobr import get_data
from tqdm.notebook import tqdm
import unicodedata
from scipy.stats import zscore
import os

# Criar pasta de exportação
if not os.path.exists("export"):
    os.makedirs("export")

# -------------------------------
# Função de normalização de texto
# -------------------------------
def normalize_txt(txt):
    txt = str(txt)
    txt = unicodedata.normalize('NFKD', txt)
    txt = txt.encode('ascii', errors='ignore').decode('utf-8').upper()
    return txt

# -------------------------------
# Lista oficial de municípios do Pantanal
# -------------------------------
municipios_pantanal = [
    "BARÃO DE MELGAÇO","CÁCERES","LAMBARI D’OESTE","POCONÉ",
    "NOSSA SENHORA DO LIVRAMENTO","SANTO ANTÔNIO DO LEVERGER","ITIQUIRA",
    "CORUMBÁ","LADÁRIO","AQUIDAUANA","MIRANDA","BODOQUENA",
    "PORTO MURTINHO","RIO VERDE DE MATO GROSSO","SONORA","COXIM"
]
municipios_norm = [normalize_txt(m) for m in municipios_pantanal]

# -------------------------------
# 1️⃣ Estações de precipitação
# -------------------------------
lista_prec = get_data.ANA.list_prec_stations()
lista_prec["City_norm"] = lista_prec["City"].apply(normalize_txt)
estacoes_prec_pantanal = lista_prec[lista_prec["City_norm"].isin(municipios_norm)].copy()
print("Estações de precipitação no Pantanal:", estacoes_prec_pantanal.shape[0])

# Baixar séries de precipitação
dados_prec = {}
for codigo in tqdm(estacoes_prec_pantanal["Code"].astype(str), desc="Baixando precipitação"):
    try:
        df = get_data.ANA.prec_data([codigo], only_consisted=False)
        df.index = pd.to_datetime(df.index)
        if not df.empty:
            # Interpolação linear para valores faltantes
            df = df.interpolate(method='time').fillna(method='bfill').fillna(method='ffill')
            # Z-score
            df_z = df.apply(zscore)
            df_z.columns = [f"{c}_zscore" for c in df_z.columns]
            # Percentis para cheias/secas
            df_perc = df.rank(pct=True)
            df_perc.columns = [f"{c}_percentile" for c in df_perc.columns]
            # Concatenar normal, zscore e percentis
            df_final = pd.concat([df, df_z, df_perc], axis=1)
            dados_prec[codigo] = df_final
    except Exception as e:
        print(f"Erro ao baixar {codigo}: {e}")

# Concatenar todas as séries de precipitação
dfs_validos = [df for df in dados_prec.values() if not df.empty]
df_prec_all = pd.concat(dfs_validos, keys=dados_prec.keys(), names=["Code", "Date"])
df_prec_all.reset_index(inplace=True)

# Exportar para Excel
df_prec_all.to_excel("export/precipitacao_pantanal.xlsx", index=False)
print("✅ Precipitação exportada para export/precipitacao_pantanal.xlsx")

# -------------------------------
# 2️⃣ Estações de vazão (flow)
# -------------------------------
lista_flu = get_data.ANA.list_flow_stations()
lista_flu["City_norm"] = lista_flu["City"].apply(normalize_txt)
estacoes_flu_pantanal = lista_flu[lista_flu["City_norm"].isin(municipios_norm)].copy()
codigos_flu = estacoes_flu_pantanal["Code"].astype(str).tolist()
print("Estações de vazão no Pantanal:", len(codigos_flu))

dados_flu = {}
for codigo in tqdm(codigos_flu, desc="Baixando vazão"):
    try:
        df = get_data.ANA.flow_data([codigo], only_consisted=False)
        df.index = pd.to_datetime(df.index)
        if not df.empty:
            # Interpolação linear para valores faltantes
            df = df.interpolate(method='time').fillna(method='bfill').fillna(method='ffill')
            # Z-score
            df_z = df.apply(zscore)
            df_z.columns = [f"{c}_zscore" for c in df_z.columns]
            # Percentis para cheias/secas
            df_perc = df.rank(pct=True)
            df_perc.columns = [f"{c}_percentile" for c in df_perc.columns]
            # Concatenar normal, zscore e percentis
            df_final = pd.concat([df, df_z, df_perc], axis=1)
            dados_flu[codigo] = df_final
    except Exception as e:
        print(f"Erro ao baixar {codigo}: {e}")

# Concatenar todas as séries de vazão
dfs_validos_flu = [df for df in dados_flu.values() if not df.empty]
df_flu_all = pd.concat(dfs_validos_flu, keys=dados_flu.keys(), names=["Code", "Date"])
df_flu_all.reset_index(inplace=True)

# Exportar para Excel
df_flu_all.to_excel("export/vazao_pantanal.xlsx", index=False)
print("✅ Vazão exportada para export/vazao_pantanal.xlsx")

"""Função preprocess_df:

Filtra DataFrames vazios

Interpola dados faltantes

Calcula STL (trend, seasonal, resid)

Calcula z-score e percentis

Função export_dfs_to_excel:

Exporta múltiplos DataFrames em um único arquivo Excel

Divide em várias planilhas se ultrapassar 1 milhão de linhas

Limita nomes das abas a 31 caracteres

Substitui a exportação direta to_excel pelo pipeline robusto acima

Mantém a estrutura de download das estações de precipitação e vazão
"""

# -------------------------------
# Importações
# -------------------------------
import pandas as pd
import numpy as np
from hydrobr import get_data
from tqdm.notebook import tqdm
import unicodedata
from scipy.stats import zscore
from statsmodels.tsa.seasonal import STL
import math
import os

# Criar pasta de exportação
EXPORT_PATH = "export"
if not os.path.exists(EXPORT_PATH):
    os.makedirs(EXPORT_PATH)

# -------------------------------
# Função de normalização de texto
# -------------------------------
def normalize_txt(txt):
    txt = str(txt)
    txt = unicodedata.normalize('NFKD', txt)
    txt = txt.encode('ascii', errors='ignore').decode('utf-8').upper()
    return txt

# -------------------------------
# Lista oficial de municípios do Pantanal
# -------------------------------
municipios_pantanal = [
    "BARÃO DE MELGAÇO","CÁCERES","LAMBARI D’OESTE","POCONÉ",
    "NOSSA SENHORA DO LIVRAMENTO","SANTO ANTÔNIO DO LEVERGER","ITIQUIRA",
    "CORUMBÁ","LADÁRIO","AQUIDAUANA","MIRANDA","BODOQUENA",
    "PORTO MURTINHO","RIO VERDE DE MATO GROSSO","SONORA","COXIM"
]
municipios_norm = [normalize_txt(m) for m in municipios_pantanal]

# -------------------------------
# Funções de pré-processamento
# -------------------------------
def preprocess_df(df, value_cols=None):
    """Filtra vazio, interpola, calcula STL, z-score e percentis"""
    if df.empty:
        return None

    df = df.sort_index().copy()

    if value_cols is None:
        value_cols = df.columns.tolist()

    # Interpolação temporal
    df[value_cols] = df[value_cols].interpolate(method='time', limit_direction='both')

    # STL
    for col in value_cols:
        stl = STL(df[col], period=12, robust=True)
        res = stl.fit()
        df[f"{col}_trend"] = res.trend
        df[f"{col}_seasonal"] = res.seasonal
        df[f"{col}_resid"] = res.resid

    # Z-score
    df_z = df[value_cols].apply(zscore)
    df_z.columns = [f"{c}_zscore" for c in df_z.columns]

    # Percentis
    df_perc = df[value_cols].rank(pct=True)
    df_perc.columns = [f"{c}_percentile" for c in df_perc.columns]

    df_final = pd.concat([df, df_z, df_perc], axis=1)
    return df_final

def export_dfs_to_excel(dfs_dict, filename, max_rows=1_000_000):
    """Exporta múltiplos DataFrames em um único Excel, dividindo em planilhas se necessário"""
    full_path = os.path.join(EXPORT_PATH, filename)
    with pd.ExcelWriter(full_path, engine="openpyxl") as writer:
        for station, df in dfs_dict.items():
            if df is None or df.empty:
                print(f"⚠️ {station}: DataFrame vazio, pulando exportação")
                continue
            num_sheets = math.ceil(len(df) / max_rows)
            for i in range(num_sheets):
                start = i * max_rows
                end = (i + 1) * max_rows
                sheet_name = f"{station}" if num_sheets == 1 else f"{station}_{i+1}"
                sheet_name = sheet_name[:31]  # limite de 31 caracteres
                df.iloc[start:end].to_excel(writer, sheet_name=sheet_name, index=True)
    print(f"✅ Exportação concluída em '{full_path}'")

# -------------------------------
# 1️⃣ Estações de precipitação
# -------------------------------
lista_prec = get_data.ANA.list_prec_stations()
lista_prec["City_norm"] = lista_prec["City"].apply(normalize_txt)
estacoes_prec_pantanal = lista_prec[lista_prec["City_norm"].isin(municipios_norm)].copy()
print("Estações de precipitação no Pantanal:", estacoes_prec_pantanal.shape[0])

dados_prec = {}
for codigo in tqdm(estacoes_prec_pantanal["Code"].astype(str), desc="Baixando precipitação"):
    try:
        df = get_data.ANA.prec_data([codigo], only_consisted=False)
        df.index = pd.to_datetime(df.index)
        if not df.empty:
            df_proc = preprocess_df(df)
            dados_prec[codigo] = df_proc
    except Exception as e:
        print(f"Erro ao baixar {codigo}: {e}")

# Exportar todas as estações de precipitação em um único Excel
export_dfs_to_excel(dados_prec, "precipitacao_pantanal.xlsx")

# -------------------------------
# 2️⃣ Estações de vazão
# -------------------------------
lista_flu = get_data.ANA.list_flow_stations()
lista_flu["City_norm"] = lista_flu["City"].apply(normalize_txt)
estacoes_flu_pantanal = lista_flu[lista_flu["City_norm"].isin(municipios_norm)].copy()
codigos_flu = estacoes_flu_pantanal["Code"].astype(str).tolist()
print("Estações de vazão no Pantanal:", len(codigos_flu))

dados_flu = {}
for codigo in tqdm(codigos_flu, desc="Baixando vazão"):
    try:
        df = get_data.ANA.flow_data([codigo], only_consisted=False)
        df.index = pd.to_datetime(df.index)
        if not df.empty:
            df_proc = preprocess_df(df)
            dados_flu[codigo] = df_proc
    except Exception as e:
        print(f"Erro ao baixar {codigo}: {e}")

# Exportar todas as estações de vazão em um único Excel
export_dfs_to_excel(dados_flu, "vazao_pantanal.xlsx")